name: Frontend Deployment

on:
  push:
    branches: [frontend]
    paths:
      - "frontend/**"
  pull_request:
    branches: [frontend]
    paths:
      - "frontend/**"

env:
  CI: true
  VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}

jobs:
  deploy-production:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/frontend'
    env:
      VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}
    steps:
      - uses: actions/checkout@v4

      - name: Install pnpm
        uses: pnpm/action-setup@v3.0.0
        with:
          version: 8

      - name: Install Vercel CLI
        run: pnpm install --global vercel@canary

      # Changed to explicitly use frontend/app directory
      - name: Pull Vercel Environment Information
        working-directory: frontend/app
        run: vercel pull --yes --environment=production --token=${{ secrets.VERCEL_TOKEN }}

      - name: Build Project Artifacts
        working-directory: frontend/app
        run: vercel build --prod --token=${{ secrets.VERCEL_TOKEN }}

      - name: Deploy Project Artifacts to Vercel
        working-directory: frontend/app
        run: vercel deploy --prebuilt --prod --token=${{ secrets.VERCEL_TOKEN }}